### ISSUE TITLE
Add Football Manager 2016 support

### ISSUE THREAD

**Issue by ThanosSiopoudis** [ThanosSiopoudis/FMScoutFramework#47]
Self-explanatory. The load process has (almost) not changed at all.
I will share my findings a little later

**Comment by s-devaney** [comment]
Any update on this?

**Comment by limkyung** [comment]
The update happens when?

**Comment by ThanosSiopoudis** [comment]
It is currently being worked on

**Comment by LazyTarget** [comment]
Anything we can do to help?

**Comment by limkyung** [comment]
how is it going? 

when can i use 2016 version?

**Comment by s-devaney** [comment]
I think this project is dead

**Comment by tthordarson** [comment]
I think there is a handful of people that are willing to help with maintain
this project. The problem is most of them aren't familiar with the core of
this library, they don't know how to get it to work for newer versions of
Football Manager. Like myself, I just know how to look for simple offsets
for entities that are already mapped. It would be incredibly helpful if
some of the key persons in this project would write more guidelines to
this. Then this project could stay alive.

**Comment by ThanosSiopoudis** [comment]
There is a (quite long) explanation on how to find the main offsets and see the loading process of the game in https://github.com/ThanosSiopoudis/FMScoutFramework/issues/1#issuecomment-120171141

I really can't put it in words in any better way than this. I'm glad to help anyone who tries to do this, but unfortunately I don't have enough free time to find the main offsets for operating systems other than OS X which is where I work MacAssistant RT on. I really have to issue providing anything you need for OS X. If someone writes up the main FM16 support with loading methods I'll be glad to add the FM16 offsets definitions.
